In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# arange:Return evenly spaced values within a given interval.

np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
# Zeroes

np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# linspace
np.linspace(0,10,3)


array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [14]:
# eye
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# Random
# rand
np.random.rand(2)

array([0.0311385 , 0.90680684])

In [16]:
np.random.rand(5,5)

array([[0.92519253, 0.80575382, 0.14913952, 0.91375928, 0.55626943],
       [0.98849607, 0.68290895, 0.23865492, 0.21740533, 0.01421066],
       [0.67298842, 0.46511618, 0.54175419, 0.3423344 , 0.61966628],
       [0.2749855 , 0.62568874, 0.80793574, 0.68238753, 0.23938255],
       [0.09049141, 0.34810417, 0.83639437, 0.26099997, 0.74764638]])

In [17]:
# randn
np.random.randn(2)

array([-0.35404791,  0.0686189 ])

In [18]:
np.random.randn(5,5)

array([[ 0.59873435,  0.73664193,  1.34229738,  0.32346183,  1.01699623],
       [ 0.05886394,  0.06748227, -2.00770748,  0.93881186,  0.05717749],
       [ 0.4550742 ,  0.62208264, -0.08688628, -0.09302526,  0.26659996],
       [-0.28416849, -0.87125789,  0.14388371,  1.39557452, -0.94086414],
       [-0.47921007, -0.46069941,  0.16405906,  0.16285391,  0.06731183]])

In [19]:
#randint
np.random.randint(1,100)

93

In [20]:
np.random.randint(1,100,10)

array([42, 79, 83, 94, 49, 74, 97, 25, 44, 62])

In [21]:
#Array Attributes and Methods
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([17, 42,  0, 21, 17,  2,  3,  9, 20,  6])

In [24]:
#Reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
#max,min,argmax,argmin
ranarr

array([17, 42,  0, 21, 17,  2,  3,  9, 20,  6])

In [26]:
ranarr.max()

42

In [27]:
ranarr.argmax()

1

In [28]:
ranarr.min()

0

In [29]:
ranarr.argmin()

2

Shape


In [30]:
# Vector
arr.shape

(25,)

In [31]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

In [35]:
#dtype

In [36]:
arr.dtype

dtype('int32')

In [37]:
#NumPy Indexing and Selection

In [38]:
import numpy as np

In [39]:
#Creating sample array
arr = np.arange(0,11)

In [40]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
#Bracket Indexing and Selection

In [42]:
#Get a value at an index
arr[8]

8

In [43]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [44]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [45]:
#Broadcasting

In [46]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [49]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [50]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
#Indexing a 2D array (matrices)

In [53]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [55]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [56]:
# Getting individual element value
arr_2d[1,0]

20

In [57]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [59]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [60]:
#Fancy Indexing

In [61]:
#Set up matrix
arr2d = np.zeros((10,10))

In [62]:
#Length of array
arr_length = arr2d.shape[1]

In [63]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [64]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [65]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [66]:
#Selection

In [67]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
bool_arr = arr>4

In [70]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
#Arithmetic

In [75]:
import numpy as np
arr = np.arange(0,10)

In [76]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [77]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [79]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [80]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [81]:
#Universal Array Functions

In [82]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [83]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [84]:
np.max(arr) #same as arr.max()

9

In [85]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [86]:
np.log(arr)

C:\Users\hp\AppData\Local\Temp/ipykernel_21864/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])